In [39]:
import requests
import re
import os
import nltk
import bs4
import scipy
import numpy
import numpy.matlib


nltk.download("punkt")
nltk.download("wordnet")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

Exercise 4.1.

In [40]:
# %% Basic file crawler
def basicfilecrawler(directory_path):
    # # Store filenames read and their text content
    # num_files_read=0
    # crawled_filenames=[]
    # crawled_texts=[]
    # directory_contentlists=gettextlist(directory_path)
    # # In this basic crawled we just process text files
    # # and do not handle subdirectories
    # directory_textfiles=directory_contentlists[0]
    # for contentitem in directory_textfiles:
    #     print('Reading file:')
    #     print(contentitem)
    #     # Open the file and read its contents
    #     temp_fullpath=os.path.join(directory_path, contentitem)
    #     temp_file=open(temp_fullpath,'r',encoding='utf-8',errors='ignore')
    #     temp_text=temp_file.read()
    #     temp_file.close()
    #     # Store the read filename and content
    #     crawled_filenames.append(contentitem)
    #     crawled_texts.append(temp_text)
    #     num_files_read=num_files_read+1
    # return(crawled_filenames,crawled_texts)

    print("Reading file:")
    temp_file = open(directory_path, "r", encoding="utf-8", errors="ignore")
    temp_text = temp_file.read()
    mytext_paragraphs=re.split(r'\n[ \n]*\n', temp_text)
    temp_file.close()
    return mytext_paragraphs

In [41]:
#%% Convert a POS tag for WordNet
def tagtowordnet(postag):
    wordnettag=-1
    if postag[0]=='N':
        wordnettag='n'
    elif postag[0]=='V':
        wordnettag='v'
    elif postag[0]=='J':
        wordnettag='a'
    elif postag[0]=='R':
        wordnettag='r'
    return(wordnettag)

#%% POS tag and lemmatize the loaded texts
# Download tagger and wordnet resources if you do not have them already
nltk.download('averaged_perceptron_tagger')
lemmatizer=nltk.stem.WordNetLemmatizer()


def lemmatizetext(nltktexttolemmatize):
    # tag the text with POS tags
    taggedtext = nltk.pos_tag(nltktexttolemmatize)
    # lemmatize each word text
    lemmatizedtext = []
    for l in range(len(taggedtext)):
        # Lemmatize a word using the WordNet converted POS tag
        wordtolemmatize = taggedtext[l][0]
        wordnettag = tagtowordnet(taggedtext[l][1])
        if wordnettag != -1:
            lemmatizedword = lemmatizer.lemmatize(wordtolemmatize, wordnettag)
        else:
            lemmatizedword = wordtolemmatize
        # store the lemmatized word
        lemmatizedtext.append(lemmatizedword)
    return(lemmatizedtext)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [42]:
# apply basic file crawler to read pg55.txt
book_content = basicfilecrawler('pg55.txt')
print(book_content)
print(len(book_content))

Reading file:
['\ufeff*** START OF THE PROJECT GUTENBERG EBOOK THE WONDERFUL WIZARD OF OZ ***\n[Illustration]', 'The Wonderful Wizard of Oz', 'by L. Frank Baum', 'This book is dedicated to my good friend & comrade\nMy Wife\nL.F.B.', 'Contents', ' Introduction\n Chapter I. The Cyclone\n Chapter II. The Council with the Munchkins\n Chapter III. How Dorothy Saved the Scarecrow\n Chapter IV. The Road Through the Forest\n Chapter V. The Rescue of the Tin Woodman\n Chapter VI.  The Cowardly Lion\n Chapter VII. The Journey to the Great Oz\n Chapter VIII. The Deadly Poppy Field\n Chapter IX. The Queen of the Field Mice\n Chapter X. The Guardian of the Gates\n Chapter XI. The Emerald City of Oz\n Chapter XII. The Search for the Wicked Witch\n Chapter XIII. The Rescue\n Chapter XIV. The Winged Monkeys\n Chapter XV. The Discovery of Oz, the Terrible\n Chapter XVI. The Magic Art of the Great Humbug\n Chapter XVII. How the Balloon Was Launched\n Chapter XVIII. Away to the South\n Chapter XIX. Attac

In [43]:
# Tokenize and lemmatize the book content
print("Tokenizing and lemmatizing the book content")

mycrawled_nltktexts=[]
for k in range(len(book_content)):    
    temp_tokenizedtext=nltk.word_tokenize(book_content[k])
    temp_nltktext=nltk.Text(temp_tokenizedtext)
    mycrawled_nltktexts.append(temp_nltktext)
print(mycrawled_nltktexts[0])

#%% Make all crawled texts lowercase
mycrawled_lowercasetexts=[]
for k in range(len(mycrawled_nltktexts)):    
    temp_lowercasetext=[]
    for l in range(len(mycrawled_nltktexts[k])):
        lowercaseword=mycrawled_nltktexts[k][l].lower()
        temp_lowercasetext.append(lowercaseword)
    temp_lowercasetest=nltk.Text(temp_lowercasetext)
    mycrawled_lowercasetexts.append(temp_lowercasetext)


Tokenizing and lemmatizing the book content
<Text:  * * * START OF THE PROJECT...>


In [44]:
#%% POS tag and lemmatize the loaded texts
# Download tagger and wordnet resources if you do not have them already
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
lemmatizer=nltk.stem.WordNetLemmatizer()

def lemmatizetext(nltktexttolemmatize):
    # Tag the text with POS tags
    taggedtext=nltk.pos_tag(nltktexttolemmatize)
    # Lemmatize each word text
    lemmatizedtext=[]
    for l in range(len(taggedtext)):
        # Lemmatize a word using the WordNet converted POS tag
        wordtolemmatize=taggedtext[l][0]
        wordnettag=tagtowordnet(taggedtext[l][1])
        if wordnettag!=-1:
            lemmatizedword=lemmatizer.lemmatize(wordtolemmatize,wordnettag)
        else:
            lemmatizedword=wordtolemmatize
        # Store the lemmatized word
        lemmatizedtext.append(lemmatizedword)
    return(lemmatizedtext)

mycrawled_lemmatizedtexts=[]
for k in range(len(mycrawled_lowercasetexts)):
    lemmatizedtext=lemmatizetext(mycrawled_lowercasetexts[k])
    lemmatizedtext=nltk.Text(lemmatizedtext)
    mycrawled_lemmatizedtexts.append(lemmatizedtext)


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [45]:
print(mycrawled_lemmatizedtexts)

[<Text:  * * * start of the project...>, <Text: the wonderful wizard of oz...>, <Text: by l. frank baum...>, <Text: this book be dedicate to my good friend...>, <Text: content...>, <Text: introduction chapter i . the cyclone chapter ii...>, <Text: introduction...>, <Text: folklore , legend , myth and fairy tale...>, <Text: yet the old time fairy tale , have...>, <Text: have this think in mind , the story...>, <Text: l. frank baum chicago , april , 1900...>, <Text: the wonderful wizard of oz...>, <Text: chapter i the cyclone...>, <Text: dorothy live in the midst of the great...>, <Text: when dorothy stood in the doorway and look...>, <Text: when aunt em come there to live she...>, <Text: uncle henry never laugh . he work hard...>, <Text: it be toto that make dorothy laugh ,...>, <Text: today , however , they be not play...>, <Text: from the far north they hear a low...>, <Text: suddenly uncle henry stand up ....>, <Text: “ there ’ s a cyclone come ,...>, <Text: aunt em drop her work an

In [46]:
#%% Find the vocabulary, in a distributed fashion

myvocabularies=[]
myindices_in_vocabularies=[]
# Find the vocabulary of each document
for k in range(len(mycrawled_lemmatizedtexts)):
    # Get unique words and where they occur
    temptext=mycrawled_lemmatizedtexts[k]
    uniqueresults=numpy.unique(temptext,return_inverse=True)
    uniquewords=uniqueresults[0]
    wordindices=uniqueresults[1]
    # Store the vocabulary and indices of document words in it
    myvocabularies.append(uniquewords)
    myindices_in_vocabularies.append(wordindices)

In [47]:
# Unify the vocabularies.
# First concatenate all vocabularies
tempvocabulary=[]  
for k in range(len(mycrawled_lemmatizedtexts)):
    tempvocabulary.extend(myvocabularies[k])
# Find the unique elements among all vocabularies
uniqueresults=numpy.unique(tempvocabulary,return_inverse=True)
unifiedvocabulary=uniqueresults[0]
wordindices=uniqueresults[1]
# Translate previous indices to the unified vocabulary.
# Must keep track where each vocabulary started in 
# the concatenated one.
vocabularystart=0
myindices_in_unifiedvocabulary=[]
for k in range(len(mycrawled_lemmatizedtexts)):
    # In order to shift word indices, we must temporarily
    # change their data type to a Numpy array
    tempindices=numpy.array(myindices_in_vocabularies[k])
    tempindices=tempindices+vocabularystart
    tempindices=wordindices[tempindices]
    myindices_in_unifiedvocabulary.append(tempindices)
    vocabularystart=vocabularystart+len(myvocabularies[k])

In [48]:
#%% Count the numbers of occurrences of each unique word
# Let's count also various statistics over the documents
unifiedvocabulary_totaloccurrencecounts=numpy.zeros((len(unifiedvocabulary),1))
unifiedvocabulary_documentcounts=numpy.zeros((len(unifiedvocabulary),1))
unifiedvocabulary_meancounts=numpy.zeros((len(unifiedvocabulary),1))
unifiedvocabulary_countvariances=numpy.zeros((len(unifiedvocabulary),1))

In [49]:
# First pass: count occurrences
for k in range(len(mycrawled_lemmatizedtexts)):
    # print(k)
    occurrencecounts=numpy.zeros((len(unifiedvocabulary),1))
    for l in range(len(myindices_in_unifiedvocabulary[k])):
        occurrencecounts[myindices_in_unifiedvocabulary[k][l]]= occurrencecounts[myindices_in_unifiedvocabulary[k][l]]+1
    unifiedvocabulary_totaloccurrencecounts= unifiedvocabulary_totaloccurrencecounts+occurrencecounts
    unifiedvocabulary_documentcounts= unifiedvocabulary_documentcounts+(occurrencecounts>0)

# Mean occurrence counts over documents
unifiedvocabulary_meancounts= unifiedvocabulary_totaloccurrencecounts/len(mycrawled_lemmatizedtexts)
    
# Second pass to count variances
for k in range(len(mycrawled_lemmatizedtexts)):
    # print(k)
    occurrencecounts=numpy.zeros((len(unifiedvocabulary),1))
    for l in range(len(myindices_in_unifiedvocabulary[k])):
        occurrencecounts[myindices_in_unifiedvocabulary[k][l]]= \
            occurrencecounts[myindices_in_unifiedvocabulary[k][l]]+1
    unifiedvocabulary_countvariances=unifiedvocabulary_countvariances+ \
        (occurrencecounts-unifiedvocabulary_meancounts)**2
unifiedvocabulary_countvariances= \
    unifiedvocabulary_countvariances/(len(mycrawled_lemmatizedtexts)-1)

In [50]:
#%% Inspect frequent words
# Sort words by largest total (or mean) occurrence count
highest_totaloccurrences_indices=numpy.argsort(\
    -1*unifiedvocabulary_totaloccurrencecounts,axis=0)
print(numpy.squeeze(unifiedvocabulary[\
    highest_totaloccurrences_indices[0:100]]))
print(numpy.squeeze(\
    unifiedvocabulary_totaloccurrencecounts[\
    highest_totaloccurrences_indices[0:100]]))

['the' ',' '.' 'and' 'be' 'to' '“' '”' 'of' 'a' 'i' 'you' 'in' 'have' 'he'
 'it' 'her' 'they' 'she' 'that' 'dorothy' 'say' 'as' 'for' 'so' 'but'
 'with' 'not' 'at' '’' 'all' 'do' 'them' 'scarecrow' 'his' ';' 'me' '?'
 'my' 'come' 'woodman' 'him' 'lion' 'oz' 'will' 'on' 'when' 'go' 'great'
 'we' 'this' 'make' 'witch' 'tin' 'ask' 'little' 'if' 'there' 'then' 'one'
 'from' 'see' 'could' 'who' 'would' 'can' 'no' 'get' 'out' 'up' 'head'
 'green' 'their' 'back' 'look' '!' 'girl' 'know' 'toto' 'down' 'think'
 'by' 'over' 's' 'again' 'what' 'answer' 'very' 'upon' 'good' 't' 'give'
 'now' 'where' 'city' 'shall' 'find' 'into' 'how' 'must']
[3005. 2703. 1938. 1666. 1466. 1118. 1084. 1065.  851.  804.  647.  492.
  482.  481.  457.  426.  410.  403.  398.  394.  369.  356.  329.  327.
  307.  301.  275.  274.  253.  248.  246.  240.  236.  227.  216.  196.
  195.  194.  191.  183.  183.  183.  183.  165.  158.  158.  157.  154.
  150.  150.  149.  146.  142.  139.  139.  139.  138.  129.  127.  12

In [51]:
# Sort words by largest total document count
highest_documentoccurrences_indices=numpy.argsort(\
    -1*unifiedvocabulary_documentcounts,axis=0)
print(numpy.squeeze(unifiedvocabulary[\
    highest_documentoccurrences_indices[1:100]]))
print(numpy.squeeze(\
    unifiedvocabulary_documentcounts[\
    highest_documentoccurrences_indices[1:100]]))

['the' ',' '“' '”' 'and' 'be' 'to' 'of' 'a' 'say' 'i' 'have' 'in'
 'dorothy' 'you' 'that' 'it' 'he' 'but' 'so' 'for' 'they' 'her' 'she'
 'with' 'scarecrow' 'all' 'not' 'as' 'do' 'at' '’' '?' 'them' ';' 'lion'
 'come' 'woodman' 'oz' 'me' 'him' 'his' 'go' 'when' 'great' 'on' 'ask'
 'this' 'my' 'will' 'little' 'tin' 'if' 'make' 'then' 'there' 'we' 'from'
 'see' 'witch' 'could' 'one' 'who' 'get' 'no' 'out' 'would' 'can' 'back'
 'up' 'girl' 'head' 'look' 'answer' '!' 'down' 'know' 'think' 'by' 'what'
 'their' 'over' 'again' 'where' 'give' 'now' 'upon' 'toto' 'shall' 's'
 'very' 'find' 'good' 't' 'city' 'into' 'must' 'walk' 'emerald']
[954. 939. 748. 733. 695. 690. 603. 471. 457. 345. 338. 334. 329. 327.
 308. 291. 278. 262. 251. 251. 250. 233. 226. 225. 210. 209. 208. 208.
 202. 198. 196. 191. 190. 169. 166. 164. 161. 158. 155. 150. 144. 143.
 141. 140. 140. 138. 138. 133. 132. 131. 127. 125. 125. 123. 120. 114.
 114. 113. 108. 107. 105. 104. 104. 103. 102.  99.  98.  97.  96.  96.
  93.  8

In [52]:
# Sort by largest variance of count over documents
highest_countvariances_indices=numpy.argsort(\
    -1*unifiedvocabulary_countvariances,axis=0)
print(numpy.squeeze(unifiedvocabulary[\
    highest_countvariances_indices[1:100]]))
print(numpy.squeeze(\
    unifiedvocabulary_countvariances[\
    highest_countvariances_indices[1:100]]))

[',' 'and' 'be' '.' 'to' 'i' 'of' 'a' 'her' 'he' 'she' 'you' 'they' 'in'
 '”' '“' 'it' 'have' 'as' 'chapter' 'that' 'for' 'with' 'them' 'my' 'his'
 'not' 'so' 'dorothy' '’' 'at' 'green' 'but' 'me' 'do' 'all' 'say' 'him'
 ';' 'witch' 'we' 'scarecrow' 'woodman' 'will' 'come' 'lion' 'make' 'on'
 'one' 'when' 'oz' '?' 'this' 'go' 'tin' 'great' 'little' 'there' 'if'
 'could' 'see' 'can' 'their' 'from' 'would' 'who' 'then' 'head' 'ask' 'no'
 'up' 'toto' 'out' 'know' 'look' '!' 's' 'get' 'over' 'think' 'down'
 'city' 'by' 'room' 't' 'back' 'girl' 'good' 'heart' 'tree' 'again' 'very'
 'upon' 'into' 'man' 'country' 'wicked' 'long' 'what']
[4.70943348 3.50245984 2.73992576 1.99947322 1.69585201 1.51167614
 1.45543105 1.43544199 0.96623693 0.93046455 0.86308088 0.78284737
 0.78185774 0.68323707 0.66028603 0.65254532 0.64338062 0.61637555
 0.54965036 0.52500347 0.45990173 0.37331223 0.34298708 0.33989803
 0.33801503 0.33105679 0.33024044 0.31810837 0.30514533 0.29679466
 0.29398749 0.29328512 0.29

In [53]:
#%% Vocabulary pruning
nltkstopwords=nltk.corpus.stopwords.words('english')
pruningdecisions=numpy.zeros((len(unifiedvocabulary),1))
for k in range(len(unifiedvocabulary)):
    # Rule 1: check the nltk stop word list
    if (unifiedvocabulary[k] in nltkstopwords):
        pruningdecisions[k]=1
    # Rule 4: if the word is too short
    if len(unifiedvocabulary[k])<2:
        pruningdecisions[k]=1
    # Rule 5: if the word is too long
    if len(unifiedvocabulary[k])>20:
        pruningdecisions[k]=1
    # Rule 5: if the word occurs less than 4 times
    if unifiedvocabulary_totaloccurrencecounts[k]<4:
        pruningdecisions[k]=1

In [54]:
#%% Inspect remaining frequent words
# Sort remaining words by largest total (or mean) occurrence count
remainingindices=numpy.squeeze(numpy.where(pruningdecisions==0)[0])
remainingvocabulary=unifiedvocabulary[remainingindices]
remainingvocabulary_totaloccurrencecounts= \
    unifiedvocabulary_totaloccurrencecounts[remainingindices]
remaining_highest_totaloccurrences_indices= \
    numpy.argsort(-1*remainingvocabulary_totaloccurrencecounts,axis=0)
print(numpy.squeeze(remainingvocabulary[remaining_highest_totaloccurrences_indices[1:500]]))
print(numpy.squeeze(remainingvocabulary_totaloccurrencecounts[ \
    remaining_highest_totaloccurrences_indices[1:500]]))

['say' 'scarecrow' 'come' 'woodman' 'lion' 'oz' 'go' 'great' 'make'
 'witch' 'tin' 'little' 'ask' 'one' 'see' 'could' 'would' 'get' 'head'
 'green' 'back' 'look' 'know' 'girl' 'toto' 'think' 'answer' 'upon' 'good'
 'give' 'shall' 'city' 'find' 'must' 'man' 'wicked' 'walk' 'long'
 'emerald' 'country' 'heart' 'away' 'take' 'room' 'well' 'us' 'tree'
 'like' 'time' 'big' 'way' 'carry' 'tell' 'never' 'brain' 'people' 'saw'
 'eye' 'reply' 'monkey' 'stand' 'live' 'many' 'first' 'chapter' 'run'
 'day' 'forest' 'friend' 'road' 'help' 'wish' 'ever' 'wizard' 'much'
 'soon' 'beast' 'keep' 'house' 'around' 'arm' 'sit' 'cry' 'thing' 'call'
 'mouse' 'old' 'oh' 'beautiful' 'land' 'shoe' 'fly' 'kill' 'woman' 'leave'
 'air' 'put' 'seem' 'quite' 'begin' 'kansas' 'voice' 'last' 'yellow'
 'return' 'pass' 'foot' 'gate' 'place' 'winged' 'cap' 'journey' 'throne'
 'next' 'leg' 'set' 'work' 'face' 'straw' 'start' 'nothing' 'also'
 'terrible' 'side' 'pretty' 'along' 'winkies' 'send' 'golden' 'afraid'
 'far' 'lay

In [55]:
#%% Get indices of documents to remaining words
oldtopruned=[]
tempind=-1
for k in range(len(unifiedvocabulary)):
    if pruningdecisions[k]==0:
        tempind=tempind+1
        oldtopruned.append(tempind)
    else:
        oldtopruned.append(-1)

#%% Create pruned texts

mycrawled_prunedtexts=[]
myindices_in_prunedvocabulary=[]
for k in range(len(mycrawled_lemmatizedtexts)):
    # print(k)
    temp_newindices=[]
    temp_newdoc=[]
    for l in range(len(mycrawled_lemmatizedtexts[k])):
        temp_oldindex=myindices_in_unifiedvocabulary[k][l]            
        temp_newindex=oldtopruned[temp_oldindex]
        if temp_newindex!=-1:
            temp_newindices.append(temp_newindex)
            temp_newdoc.append(unifiedvocabulary[temp_oldindex])
    mycrawled_prunedtexts.append(temp_newdoc)
    myindices_in_prunedvocabulary.append(temp_newindices)

In [56]:
# %% Create TF-IDF vectors
n_docs = len(mycrawled_prunedtexts)
n_vocab = len(remainingvocabulary)

# Matrix of term frequencies
tfmatrix = scipy.sparse.lil_matrix((n_docs, n_vocab))
# Row vector of document frequencies
dfvector = scipy.sparse.lil_matrix((1, n_vocab))
# Loop over documents
for k in range(n_docs):
    # Row vector of which words occurred in this document
    temp_dfvector = scipy.sparse.lil_matrix((1, n_vocab))
    # Loop over words
    for l in range(len(mycrawled_prunedtexts[k])):
        # Add current word to term-frequency count and document-count
        currentword = myindices_in_prunedvocabulary[k][l]
        tfmatrix[k, currentword] = tfmatrix[k, currentword] + 1
        temp_dfvector[0, currentword] = 1
    # Add which words occurred in this document to overall document counts
    dfvector = dfvector + temp_dfvector

In [57]:
# length-normalized frequency for the TF part
for i in range(n_docs):
    for j in range(len(tfmatrix.data[i])):
        tfmatrix.data[i][j] = tfmatrix.data[i][j] / len(tfmatrix.data[i])


In [58]:
# Use the count statistics to compute the tf-idf matrix
tfidfmatrix=scipy.sparse.lil_matrix((n_docs,n_vocab))
# Let's use raw term count, and smoothed logarithmic idf
idfvector = numpy.squeeze(numpy.array(dfvector.todense()))
idfvector=numpy.log(1+((idfvector+1)**-1)*n_docs)
for k in range(n_docs):
    # Combine the tf and idf terms
    # # tfidfmatrix[k,:]=tfmatrix[k,:]*idfvector
    # fixing dimensionality mismatch
    tempindices = numpy.nonzero(tfmatrix[k, :])[1]
    tfterm = numpy.squeeze(numpy.array(tfmatrix[k, tempindices].todense()))
    tfidfmatrix[k, tempindices] = tfterm * idfvector[tempindices]


In [59]:
#%% Use the TF-IDF matrix as data to be clustered
X=tfidfmatrix
# Normalize the documents to unit vector norm
tempnorms=numpy.squeeze(numpy.array(numpy.sum(X.multiply(X),axis=1)))
# If any documents have zero norm, avoid dividing them by zero
tempnorms[tempnorms==0]=1
X=scipy.sparse.diags(tempnorms**-0.5).dot(X)

n_data=numpy.shape(X)[0]
n_dimensions=numpy.shape(X)[1]

In [60]:
#%% Initialize the Gaussian mixture model

# Function to initialize the Gaussian mixture model, create component parameters
def initialize_mixturemodel(X,n_components):
    # Create lists of sparse matrices to hold the parameters
    n_dimensions=numpy.shape(X)[1]
    n_data = numpy.shape(X)[0]
    mixturemodel_means=scipy.sparse.lil_matrix((n_components,n_dimensions))
    mixturemodel_weights=numpy.zeros((n_components))
    mixturemodel_covariances=[]
    mixturemodel_inversecovariances=[]
    for k in range(n_components):
        tempcovariance=scipy.sparse.lil_matrix((n_dimensions,n_dimensions))    
        mixturemodel_covariances.append(tempcovariance)
        tempinvcovariance=scipy.sparse.lil_matrix((n_dimensions,n_dimensions))   
        mixturemodel_inversecovariances.append(tempinvcovariance)

    # Initialize the parameters
    for k in range(n_components):
        mixturemodel_weights[k]=1/n_components
        # Pick a random data point as the initial mean
        tempindex=scipy.stats.randint.rvs(low=0,high=n_data)
        mixturemodel_means[k]=X[tempindex,:].toarray()  
        # Initialize the covariance matrix to be spherical
        for l in range(n_dimensions):
            mixturemodel_covariances[k][l,l]=1
            mixturemodel_inversecovariances[k][l,l]=1
    return(mixturemodel_weights,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances)

In [61]:
def run_estep(X,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances,mixturemodel_weights):
    # For each component, compute terms that do not involve data
    meanterms=numpy.zeros((n_components))
    logdeterminants=numpy.zeros((n_components))
    logconstantterms=numpy.zeros((n_components))
    for k in range(n_components):
        # Compute mu_k*inv(Sigma_k)*mu_k
        meanterms[k]=(mixturemodel_means[k,:]* mixturemodel_inversecovariances[k]*mixturemodel_means[k,:].T)[0,0]
        # Compute determinant of Sigma_k. For a diagonal matrix 
        # this is just the product of the main diagonal
        logdeterminants[k]=numpy.sum(numpy.log(mixturemodel_covariances[k].diagonal(0)))
        # Compute constant term beta_k * 1/(|Sigma_k|^1/2)
        # Omit the (2pi)^d/2 as it cancels out
        logconstantterms[k]=numpy.log(mixturemodel_weights[k]) - 0.5*logdeterminants[k]

    # print('E-step part2 ')
    # Compute terms that involve distances of data from components
    xnorms=numpy.zeros((n_data,n_components))
    xtimesmu=numpy.zeros((n_data,n_components))
    for k in range(n_components):
        # print(k)
        xnorms[:,k]=(X*mixturemodel_inversecovariances[k]*X.T).diagonal(0)
        xtimesmu[:,k]=numpy.squeeze((X*mixturemodel_inversecovariances[k]* mixturemodel_means[k,:].T).toarray())
    xdists=xnorms+numpy.matlib.repmat(meanterms,n_data,1)-2*xtimesmu        
    # Substract maximal term before exponent (cancels out) to maintain computational precision
    numeratorterms=logconstantterms-xdists/2
    numeratorterms-=numpy.matlib.repmat(numpy.max(numeratorterms,axis=1),n_components,1).T
    numeratorterms=numpy.exp(numeratorterms)
    mixturemodel_componentmemberships=numeratorterms/numpy.matlib.repmat( numpy.sum(numeratorterms,axis=1),n_components,1).T
    return(mixturemodel_componentmemberships)

In [62]:
def run_mstep_sumweights(mixturemodel_componentmemberships):
    # Compute total weight per component
    mixturemodel_weights=numpy.sum(mixturemodel_componentmemberships,axis=0)
    return(mixturemodel_weights)

def run_mstep_means(X,mixturemodel_componentmemberships,mixturemodel_weights):
    # Update component means
    mixturemodel_means=scipy.sparse.lil_matrix((n_components,n_dimensions))
    for k in range(n_components):
        mixturemodel_means[k,:]= numpy.sum(scipy.sparse.diags(mixturemodel_componentmemberships[:,k]).dot(X),axis=0)
        mixturemodel_means[k,:]/=mixturemodel_weights[k]
    return(mixturemodel_means)

def run_mstep_covariances(X,mixturemodel_componentmemberships,mixturemodel_weights,mixturemodel_means):
    # Update diagonal component covariance matrices
    n_dimensions=numpy.shape(X)[1]
    n_components=numpy.shape(mixturemodel_componentmemberships)[1]
    tempcovariances=numpy.zeros((n_components,n_dimensions))
    mixturemodel_covariances=[]
    mixturemodel_inversecovariances=[]
    for k in range(n_components):
        tempcovariances[k,:]= numpy.sum(scipy.sparse.diags(mixturemodel_componentmemberships[:,k]).dot(X.multiply(X)),axis=0) \
            -mixturemodel_means[k,:].multiply(mixturemodel_means[k,:])*mixturemodel_weights[k]
        tempcovariances[k,:]/=mixturemodel_weights[k]
        # Convert to sparse matrices
        tempepsilon=1e-10
        # Add a small regularization term
        temp_covariance=scipy.sparse.diags(tempcovariances[k,:]+tempepsilon)
        temp_inversecovariance=scipy.sparse.diags((tempcovariances[k,:]+tempepsilon)**-1)
        mixturemodel_covariances.append(temp_covariance)
        mixturemodel_inversecovariances.append(temp_inversecovariance) 
    return(mixturemodel_covariances,mixturemodel_inversecovariances)   

def run_mstep_normalizeweights(mixturemodel_weights):
    # Update mixture-component prior probabilities
    mixturemodel_weights/=sum(mixturemodel_weights)
    return(mixturemodel_weights)

In [63]:
#%% Perform the EM algorithm iterations    
def perform_emalgorithm(X,n_components,n_emiterations):
    mixturemodel_weights,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances=initialize_mixturemodel(X,n_components)
    for t in range(n_emiterations):
        # ====== E-step: Compute the component membership
        # probabilities of each data point ======
        # print('E-step ' + str(t))
        mixturemodel_componentmemberships=run_estep(X,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances,mixturemodel_weights)    
        # ====== M-step: update component parameters======
        # print('M-step ' + str(t))
        # print('M-step part1 ' + str(t))
        mixturemodel_weights=run_mstep_sumweights(mixturemodel_componentmemberships)
        # print('M-step part2 ' + str(t))
        mixturemodel_means=run_mstep_means(X,mixturemodel_componentmemberships,mixturemodel_weights)
        # print('M-step part3 ' + str(t))
        mixturemodel_covariances,mixturemodel_inversecovariances=run_mstep_covariances(X, mixturemodel_componentmemberships,mixturemodel_weights,mixturemodel_means)
        # print('M-step part4 ' + str(t))
        mixturemodel_weights=run_mstep_normalizeweights(mixturemodel_weights)
    return(mixturemodel_weights,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances)


In [64]:
# Try out the functions we just defined on the data
n_components=10
n_emiterations=100
mixturemodel_weights,mixturemodel_means,mixturemodel_covariances, mixturemodel_inversecovariances = perform_emalgorithm(X,n_components,n_emiterations)


In [65]:
# Find top 10 words for each cluster
for k in range(n_components):
    print(k)
    highest_dimensionweight_indices=numpy.argsort(-numpy.squeeze(mixturemodel_means[k,:].toarray()),axis=0)       
    print(' '.join(remainingvocabulary[highest_dimensionweight_indices[1:10]]))

0
room soldier dorothy throne gate dress come little morning
1
sit think say woodman go moment certainly dorothy look
2
dorothy scarecrow say answer woodman oz shall go inquire
3
yellow brick back get dorothy way must lion say
4
us scarecrow dorothy back shall brain kansas get try
5
say great terrible chapter dorothy voice wizard ask want
6
one leg time say eye dorothy three know balloon
7
woodman tin say thing lion world may bad brain
8
dorothy thank ask scarecrow friend go like look ground
9
woodman head axe tin lion quick witch chop foot


In [66]:
# Version 2 - Get documents closest to component mean, i.e. highest p(d|k).
# ---The computation of distances here is the same as done in the E-step of EM---
# For each component, compute terms that do not involve data
meanterms=numpy.zeros((n_components))
logdeterminants=numpy.zeros((n_components))
logconstantterms=numpy.zeros((n_components))
for k in range(n_components):
    # Compute mu_k*inv(Sigma_k)*mu_k
    meanterms[k]=(mixturemodel_means[k,:] * mixturemodel_inversecovariances[k]*mixturemodel_means[k,:].T)[0,0]
# Compute terms that involve distances of data from components
xnorms=numpy.zeros((n_data,n_components))
xtimesmu=numpy.zeros((n_data,n_components))
for k in range(n_components):
    xnorms[:,k]=(X*mixturemodel_inversecovariances[k]*X.T).diagonal(0)
    xtimesmu[:,k]=numpy.squeeze((X*mixturemodel_inversecovariances[k] * mixturemodel_means[k,:].T).toarray())
xdists=xnorms+numpy.matlib.repmat(meanterms,n_data,1)-2*xtimesmu

for k in range(n_components):
    tempdists=numpy.array(numpy.squeeze(xdists[:,k]))
    highest_componentprob_indices=numpy.argsort(-1*tempdists,axis=0)
    print(k)
    print(highest_componentprob_indices[0:10])
    print(' '.join(mycrawled_nltktexts[highest_componentprob_indices[0]]))

0
[ 875 1017  840    5  225  752 1055  270  359  829]
“ Drink . ”
1
[   4  804  809   49  185 1027  134  623  520  174]
Contents
2
[   4 1017  878  595  857   22   20  939 1076   87]
Contents
3
[  4 809 875 111  49 270 595 137 202 413]
Contents
4
[ 673   33  875 1017  882  532  878  111    5 1129]
Chapter XIII The Rescue
5
[1017  875  878 1013  857  370   20  114  608  357]
“ Don ’ t chase me ! Don ’ t chase me ! ”
6
[ 889  808  330  875 1135  809    4  429  673   12]
“ How can I cross the desert ? ” she inquired .
7
[1017  875  419  111  775  370  190  191 1076  752]
“ Don ’ t chase me ! Don ’ t chase me ! ”
8
[1135  429    4  809 1017  419  878  840    5  806]
Chapter XXIV Home Again
9
[ 673    4  429 1135  882    5  134  867  939  225]
Chapter XIII The Rescue


The 10 words with highest abosolute value in the mean and the paragraph with highest membership probability in that component are not match. This is because the 10 words with highest absolute value in the mean are the words that are most important for the component, while the paragraph with highest membership probability in that component is the paragraph that is most similar to the component, which is not necessarily the paragraph that contains the most words that are important for the component.

Exercise 4.2: Comparison of TF-IDF variants.

(a) Find the longest paragraph of "The Wonderful Wizard of Oz". Report the text of the paragraph.

(b) Using the same processing as in Exercise 4.1 (a)-(b), create a TF-IDF representation for the longest paragraph, with three options: 

▪ Length-normalized frequency (TF) and Smoothed logarithmic inverse document frequency (IDF)

▪ Logarithm of the count (TF) and Smoothed logarithmic inverse document frequency (IDF)

▪ Count relative to most frequent term (TF) and Version proportional to most common term (IDF)

For each option, report the 20 words with highest TF-IDF weight. Discuss the results; does any one of the options seem to match the semantic meaning of the paragraph better?

Report the requested text, statistics, discussion, and your code.

In [67]:
# Take the longest paragraph only from book_content
longest_paragraph = [max(book_content, key=len)]
print(longest_paragraph)
print(longest_paragraph[0])


['She left Dorothy alone and went back to the others. These she also led\nto rooms, and each one of them found himself lodged in a very pleasant\npart of the Palace. Of course this politeness was wasted on the\nScarecrow; for when he found himself alone in his room he stood\nstupidly in one spot, just within the doorway, to wait till morning. It\nwould not rest him to lie down, and he could not close his eyes; so he\nremained all night staring at a little spider which was weaving its web\nin a corner of the room, just as if it were not one of the most\nwonderful rooms in the world. The Tin Woodman lay down on his bed from\nforce of habit, for he remembered when he was made of flesh; but not\nbeing able to sleep, he passed the night moving his joints up and down\nto make sure they kept in good working order. The Lion would have\npreferred a bed of dried leaves in the forest, and did not like being\nshut up in a room; but he had too much sense to let this worry him, so\nhe sprang upon th

In [68]:
# Tokenize and lemmatize the longest paragraph
print("Tokenizing and lemmatizing the longest paragraph")

longest_paragraph_mycrawled_nltktexts=[]
for k in range(len(longest_paragraph)):
    temp_tokenizedtext=nltk.word_tokenize(longest_paragraph[k])
    temp_nltktext=nltk.Text(temp_tokenizedtext)
    longest_paragraph_mycrawled_nltktexts.append(temp_nltktext)
print(longest_paragraph_mycrawled_nltktexts[0])

#%% Make all crawled texts lowercase
longest_paragraph_mycrawled_lowercasetexts=[]
for k in range(len(longest_paragraph_mycrawled_nltktexts)):
    temp_lowercasetext=[]
    for l in range(len(longest_paragraph_mycrawled_nltktexts[k])):
        lowercaseword=longest_paragraph_mycrawled_nltktexts[k][l].lower()
        temp_lowercasetext.append(lowercaseword)
    temp_lowercasetest=nltk.Text(temp_lowercasetext)
    longest_paragraph_mycrawled_lowercasetexts.append(temp_lowercasetext)


Tokenizing and lemmatizing the longest paragraph
<Text: She left Dorothy alone and went back to...>


In [69]:
# POS tag and lemmatize the loaded texts
lemmatizer=nltk.stem.WordNetLemmatizer()
longest_paragraph_mycrawled_lemmatizedtexts=[]
for k in range(len(longest_paragraph_mycrawled_lowercasetexts)):
    lemmatizedtext=lemmatizetext(longest_paragraph_mycrawled_lowercasetexts[k])
    lemmatizedtext=nltk.Text(lemmatizedtext)
    longest_paragraph_mycrawled_lemmatizedtexts.append(lemmatizedtext)

# Find the vocabulary of the longest paragraph
longest_paragraph_myvocabularies=[]
longest_paragraph_myindices_in_vocabularies=[]
# Find the vocabulary of each document
for k in range(len(longest_paragraph_mycrawled_lemmatizedtexts)):
    # Get unique words and where they occur
    temptext=longest_paragraph_mycrawled_lemmatizedtexts[k]
    uniqueresults=numpy.unique(temptext,return_inverse=True)
    uniquewords=uniqueresults[0]
    wordindices=uniqueresults[1]
    # Store the vocabulary and indices of document words in it
    longest_paragraph_myvocabularies.append(uniquewords)
    longest_paragraph_myindices_in_vocabularies.append(wordindices)

In [70]:
# Unify the vocabularies.
# First concatenate all vocabularies
longest_paragraph_tempvocabulary=[]
for k in range(len(longest_paragraph_mycrawled_lemmatizedtexts)):
    longest_paragraph_tempvocabulary.extend(longest_paragraph_myvocabularies[k])
# Find the unique elements among all vocabularies
longest_paragraph_uniqueresults=numpy.unique(longest_paragraph_tempvocabulary,return_inverse=True)
longest_paragraph_unifiedvocabulary=longest_paragraph_uniqueresults[0]
longest_paragraph_wordindices=longest_paragraph_uniqueresults[1]
# Translate previous indices to the unified vocabulary.
# Must keep track where each vocabulary started in
# the concatenated one.
longest_paragraph_vocabularystart=0
longest_paragraph_myindices_in_unifiedvocabulary=[]
for k in range(len(longest_paragraph_mycrawled_lemmatizedtexts)):
    # In order to shift word indices, we must temporarily
    # change their data type to a Numpy array
    tempindices=numpy.array(longest_paragraph_myindices_in_vocabularies[k])
    tempindices=tempindices+longest_paragraph_vocabularystart
    tempindices=longest_paragraph_wordindices[tempindices]
    longest_paragraph_myindices_in_unifiedvocabulary.append(tempindices)
    longest_paragraph_vocabularystart=longest_paragraph_vocabularystart+len(longest_paragraph_myvocabularies[k])


In [71]:
# Count the numbers of occurrences of each unique word
# Let's count also various statistics over the documents
longest_paragraph_unifiedvocabulary_totaloccurrencecounts=numpy.zeros((len(longest_paragraph_unifiedvocabulary),1))
longest_paragraph_unifiedvocabulary_documentcounts=numpy.zeros((len(longest_paragraph_unifiedvocabulary),1))
longest_paragraph_unifiedvocabulary_meancounts=numpy.zeros((len(longest_paragraph_unifiedvocabulary),1))


In [72]:
# First pass: count occurrences
for k in range(len(longest_paragraph_mycrawled_lemmatizedtexts)):
    # print(k)
    longest_paragraph_occurrencecounts=numpy.zeros((len(longest_paragraph_unifiedvocabulary),1))
    for l in range(len(longest_paragraph_myindices_in_unifiedvocabulary[k])):
        longest_paragraph_occurrencecounts[longest_paragraph_myindices_in_unifiedvocabulary[k][l]]= longest_paragraph_occurrencecounts[longest_paragraph_myindices_in_unifiedvocabulary[k][l]]+1
    longest_paragraph_unifiedvocabulary_totaloccurrencecounts= longest_paragraph_unifiedvocabulary_totaloccurrencecounts+longest_paragraph_occurrencecounts
    longest_paragraph_unifiedvocabulary_documentcounts= longest_paragraph_unifiedvocabulary_documentcounts+(longest_paragraph_occurrencecounts>0)
    
# Mean occurrence counts over documents
longest_paragraph_unifiedvocabulary_meancounts= longest_paragraph_unifiedvocabulary_totaloccurrencecounts/len(longest_paragraph_mycrawled_lemmatizedtexts)

In [73]:

#%% Inspect frequent words
# Sort words by largest total (or mean) occurrence count
longest_paragraph_highest_totaloccurrences_indices=numpy.argsort(-1*longest_paragraph_unifiedvocabulary_totaloccurrencecounts,axis=0)
print(numpy.squeeze(longest_paragraph_unifiedvocabulary[longest_paragraph_highest_totaloccurrences_indices[0:100]]))
print(numpy.squeeze(longest_paragraph_unifiedvocabulary_totaloccurrencecounts[longest_paragraph_highest_totaloccurrences_indices[0:100]]))


['the' ',' 'in' 'he' 'of' 'a' 'to' 'and' '.' 'be' 'not' 'room' ';'
 'himself' 'his' 'down' 'one' 'bed' 'up' 'she' 'night' 'make' 'like'
 'just' 'it' 'so' 'this' 'when' 'him' 'on' 'have' 'would' 'alone' 'for'
 'find' 'but' 'forest' 'sure' 'stupidly' 'star' 'stand' 'spring' 'spot'
 'spider' 'asleep' 'shut' 'as' 'at' 'sense' 'scarecrow' 'back' 'roll'
 'rest' 'remember' 'sleep' 'them' 'they' 'remain' 'world' 'work' 'woodman'
 'wonderful' 'within' 'which' 'able' 'web' 'these' 'weave' 'wait' 'very'
 'upon' 'all' 'too' 'tin' 'till' 'also' 'waste' 'purr' 'politeness'
 'force' 'leave' 'leaf' 'lead' 'lay' 'keep' 'doorway' 'joint' 'its' 'let'
 'dorothy' 'if' 'each' 'eye' 'flesh' 'habit' 'good' 'go' 'from' 'dried'
 'prefer']
[12.  9.  9.  9.  8.  7.  7.  7.  6.  6.  5.  5.  4.  4.  4.  3.  3.  3.
  3.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  

In [74]:
# Sort words by largest total document count
longest_paragraph_highest_documentoccurrences_indices=numpy.argsort(-1*longest_paragraph_unifiedvocabulary_documentcounts,axis=0)
print(numpy.squeeze(longest_paragraph_unifiedvocabulary[longest_paragraph_highest_documentoccurrences_indices[1:100]]))
print(numpy.squeeze(longest_paragraph_unifiedvocabulary_documentcounts[longest_paragraph_highest_documentoccurrences_indices[1:100]]))


['sleep' 'shut' 'she' 'sense' 'scarecrow' 'room' 'roll' 'rest' 'remember'
 'remain' 'purr' 'prefer' 'so' 'politeness' 'pass' 'part' 'palace'
 'others' 'order' 'one' 'on' 'of' 'not' 'night' 'much' 'move' 'pleasant'
 'spider' 'spot' 'spring' 'world' 'work' 'woodman' 'wonderful' 'within'
 'which' 'when' 'web' 'weave' 'waste' 'wait' 'very' 'upon' 'up' 'too' 'to'
 'tin' 'till' 'this' 'they' 'these' 'them' 'the' 'sure' 'stupidly' 'star'
 'stand' 'most' 'morning' 'minute' 'make' 'eye' 'each' 'dried' 'down'
 'dorothy' 'doorway' 'do' 'course' 'could' 'corner' 'close' 'cat' 'but'
 'bed' 'be' 'back' 'at' 'asleep' 'as' 'and' 'also' 'alone' 'all' 'able'
 'a' ';' '.' 'find' 'worry' 'flesh' 'force' 'lodge' 'little' 'lion' 'like'
 'lie' 'let' 'leave']
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [75]:
#%% Vocabulary pruning
nltkstopwords=nltk.corpus.stopwords.words('english')
longest_paragraph_pruningdecisions=numpy.zeros((len(longest_paragraph_unifiedvocabulary),1))
for k in range(len(longest_paragraph_unifiedvocabulary)):
    ...
    # Rule 1: check the nltk stop word list
    # if (longest_paragraph_unifiedvocabulary[k] in nltkstopwords):
    #     longest_paragraph_pruningdecisions[k]=1
    # # Rule 4: if the word is too short
    # if len(longest_paragraph_unifiedvocabulary[k])<2:
    #     longest_paragraph_pruningdecisions[k]=1
    # # Rule 5: if the word is too long
    # if len(longest_paragraph_unifiedvocabulary[k])>20:
    #     longest_paragraph_pruningdecisions[k]=1
    # # Rule 5: if the word occurs less than 4 times
    # if longest_paragraph_unifiedvocabulary_totaloccurrencecounts[k]<4:
    #     longest_paragraph_pruningdecisions[k]=1

In [76]:
#%% Inspect remaining frequent words
# Sort remaining words by largest total (or mean) occurrence count
longest_paragraph_remainingindices=numpy.squeeze(numpy.where(longest_paragraph_pruningdecisions==0)[0])
longest_paragraph_remainingvocabulary=longest_paragraph_unifiedvocabulary[longest_paragraph_remainingindices]
longest_paragraph_remainingvocabulary_totaloccurrencecounts= longest_paragraph_unifiedvocabulary_totaloccurrencecounts[longest_paragraph_remainingindices]
longest_paragraph_remaining_highest_totaloccurrences_indices= numpy.argsort(-1*longest_paragraph_remainingvocabulary_totaloccurrencecounts,axis=0)
# print(numpy.squeeze(longest_paragraph_remainingvocabulary[longest_paragraph_remaining_highest_totaloccurrences_indices[1:500]]))
# print(numpy.squeeze(longest_paragraph_remainingvocabulary_totaloccurrencecounts[longest_paragraph_remaining_highest_totaloccurrences_indices[1:500]]))
print(longest_paragraph_remainingvocabulary)
print(longest_paragraph_remainingvocabulary_totaloccurrencecounts)

[',' '.' ';' 'a' 'able' 'all' 'alone' 'also' 'and' 'as' 'asleep' 'at'
 'back' 'be' 'bed' 'but' 'cat' 'close' 'corner' 'could' 'course' 'do'
 'doorway' 'dorothy' 'down' 'dried' 'each' 'eye' 'find' 'flesh' 'for'
 'force' 'forest' 'from' 'go' 'good' 'habit' 'have' 'he' 'him' 'himself'
 'his' 'if' 'in' 'it' 'its' 'joint' 'just' 'keep' 'lay' 'lead' 'leaf'
 'leave' 'let' 'lie' 'like' 'lion' 'little' 'lodge' 'make' 'minute'
 'morning' 'most' 'move' 'much' 'night' 'not' 'of' 'on' 'one' 'order'
 'others' 'palace' 'part' 'pass' 'pleasant' 'politeness' 'prefer' 'purr'
 'remain' 'remember' 'rest' 'roll' 'room' 'scarecrow' 'sense' 'she' 'shut'
 'sleep' 'so' 'spider' 'spot' 'spring' 'stand' 'star' 'stupidly' 'sure'
 'the' 'them' 'these' 'they' 'this' 'till' 'tin' 'to' 'too' 'up' 'upon'
 'very' 'wait' 'waste' 'weave' 'web' 'when' 'which' 'within' 'wonderful'
 'woodman' 'work' 'world' 'worry' 'would']
[[ 9.]
 [ 6.]
 [ 4.]
 [ 7.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 7.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 6.]
 [ 

In [77]:
#%% Get indices of documents to remaining words
longest_paragraph_oldtopruned=[]
longest_paragraph_tempind=-1
for k in range(len(longest_paragraph_unifiedvocabulary)):
    if longest_paragraph_pruningdecisions[k]==0:
        longest_paragraph_tempind=longest_paragraph_tempind+1
        longest_paragraph_oldtopruned.append(longest_paragraph_tempind)
    else:
        longest_paragraph_oldtopruned.append(-1)
    
#%% Create pruned texts
longest_paragraph_mycrawled_prunedtexts=[]
longest_paragraph_myindices_in_prunedvocabulary=[]
for k in range(len(longest_paragraph_mycrawled_lemmatizedtexts)):
    # print(k)
    longest_paragraph_temp_newindices=[]
    longest_paragraph_temp_newdoc=[]
    for l in range(len(longest_paragraph_mycrawled_lemmatizedtexts[k])):
        longest_paragraph_temp_oldindex=longest_paragraph_myindices_in_unifiedvocabulary[k][l]            
        longest_paragraph_temp_newindex=longest_paragraph_oldtopruned[longest_paragraph_temp_oldindex]
        if longest_paragraph_temp_newindex!=-1:
            longest_paragraph_temp_newindices.append(longest_paragraph_temp_newindex)
            longest_paragraph_temp_newdoc.append(longest_paragraph_unifiedvocabulary[longest_paragraph_temp_oldindex])
    longest_paragraph_mycrawled_prunedtexts.append(longest_paragraph_temp_newdoc)
    longest_paragraph_myindices_in_prunedvocabulary.append(longest_paragraph_temp_newindices)
        

In [78]:
# %% Create TF-IDF vectors
longest_paragraph_n_docs = len(longest_paragraph_mycrawled_prunedtexts)
longest_paragraph_n_vocab = len(longest_paragraph_remainingvocabulary)
# Matrix of term frequencies
longest_paragraph_tfmatrix = scipy.sparse.lil_matrix((longest_paragraph_n_docs, longest_paragraph_n_vocab))
# Row vector of document frequencies
longest_paragraph_dfvector = scipy.sparse.lil_matrix((1, longest_paragraph_n_vocab))
# Loop over documents
for k in range(longest_paragraph_n_docs):
    # Row vector of which words occurred in this document
    longest_paragraph_temp_dfvector = scipy.sparse.lil_matrix((1, longest_paragraph_n_vocab))
    # Loop over words
    for l in range(len(longest_paragraph_mycrawled_prunedtexts[k])):
        # Add current word to term-frequency count and document-count
        currentword = longest_paragraph_myindices_in_prunedvocabulary[k][l]
        longest_paragraph_tfmatrix[k, currentword] = longest_paragraph_tfmatrix[k, currentword] + 1
        longest_paragraph_temp_dfvector[0, currentword] = 1
    # Add which words occurred in this document to overall document counts
    longest_paragraph_dfvector = longest_paragraph_dfvector + longest_paragraph_temp_dfvector

In [79]:

# Use the count statistics to compute the tf-idf matrix
longest_paragraph_tfidfmatrix=scipy.sparse.lil_matrix((longest_paragraph_n_docs,longest_paragraph_n_vocab))
# Let's use raw term count, and smoothed logarithmic idf
longest_paragraph_idfvector = numpy.squeeze(numpy.array(longest_paragraph_dfvector.todense()))
longest_paragraph_idfvector=numpy.log(1+((longest_paragraph_idfvector+1)**-1)*longest_paragraph_n_docs)
for k in range(longest_paragraph_n_docs):
    # Combine the tf and idf terms
    # # longest_paragraph_tfidfmatrix[k,:]=longest_paragraph_tfmatrix[k,:]*longest_paragraph_idfvector
    # fixing dimensionality mismatch
    longest_paragraph_tempindices = numpy.nonzero(longest_paragraph_tfmatrix[k, :])[1]
    longest_paragraph_tfterm = numpy.squeeze(numpy.array(longest_paragraph_tfmatrix[k, longest_paragraph_tempindices].todense()))
    longest_paragraph_tfidfmatrix[k, longest_paragraph_tempindices] = longest_paragraph_tfterm * longest_paragraph_idfvector[longest_paragraph_tempindices]
#%% Use the TF-IDF matrix as data to be clustered
longest_paragraph_X=longest_paragraph_tfidfmatrix
# Normalize the documents to unit vector norm
longest_paragraph_tempnorms=numpy.squeeze(numpy.array(numpy.sum(longest_paragraph_X.multiply(longest_paragraph_X),axis=1)))
# If any documents have zero norm, avoid dividing them by zero
longest_paragraph_tempnorms[longest_paragraph_tempnorms==0]=1
longest_paragraph_tempnorms = numpy.array([longest_paragraph_tempnorms])
longest_paragraph_X=scipy.sparse.diags(longest_paragraph_tempnorms**-0.5).dot(longest_paragraph_X)

longest_paragraph_n_data=numpy.shape(longest_paragraph_X)[0]
longest_paragraph_n_dimensions=numpy.shape(longest_paragraph_X)[1]
print(longest_paragraph_n_data)
print(longest_paragraph_n_dimensions)


1
122


In [80]:

# report the 20 words with highest TF-IDF weight using the logarithm of the count and smoothed idf
print("report the 20 words with highest TF-IDF weight using the logarithm of the count and smoothed idf")
longest_paragraph_tf_idf_weights = numpy.squeeze(numpy.array(longest_paragraph_X[0, :].todense()))
longest_paragraph_highest_tf_idf_indices = numpy.argsort(-1*longest_paragraph_tf_idf_weights,axis=0)
# print(longest_paragraph_remainingvocabulary[longest_paragraph_highest_tf_idf_indices[0:20]])
# print(longest_paragraph_tf_idf_weights[longest_paragraph_highest_tf_idf_indices[0:20]])

report the 20 words with highest TF-IDF weight using the logarithm of the count and smoothed idf


In [81]:
# Use the count statistics to compute the tf-idf matrix
longest_paragraph_tfidfmatrix=scipy.sparse.lil_matrix((longest_paragraph_n_docs,longest_paragraph_n_vocab))
# Let's use raw term count, and smoothed logarithmic idf
longest_paragraph_idfvector = numpy.squeeze(numpy.array(longest_paragraph_dfvector.todense()))
# length-normalized frequency for the TF part
longest_paragraph_idfvector = longest_paragraph_idfvector / numpy.sum(longest_paragraph_idfvector)
for k in range(longest_paragraph_n_docs):
    # Combine the tf and idf terms
    # # longest_paragraph_tfidfmatrix[k,:]=longest_paragraph_tfmatrix[k,:]*longest_paragraph_idfvector
    # fixing dimensionality mismatch
    longest_paragraph_tempindices = numpy.nonzero(longest_paragraph_tfmatrix[k, :])[1]
    longest_paragraph_tfterm = numpy.squeeze(numpy.array(longest_paragraph_tfmatrix[k, longest_paragraph_tempindices].todense()))
    longest_paragraph_tfidfmatrix[k, longest_paragraph_tempindices] = longest_paragraph_tfterm * longest_paragraph_idfvector[longest_paragraph_tempindices]
#%% Use the TF-IDF matrix as data to be clustered
longest_paragraph_X=longest_paragraph_tfidfmatrix
# Normalize the documents to unit vector norm
longest_paragraph_tempnorms=numpy.squeeze(numpy.array(numpy.sum(longest_paragraph_X.multiply(longest_paragraph_X),axis=1)))
# If any documents have zero norm, avoid dividing them by zero
longest_paragraph_tempnorms[longest_paragraph_tempnorms==0]=1
longest_paragraph_tempnorms = numpy.array([longest_paragraph_tempnorms])
longest_paragraph_X=scipy.sparse.diags(longest_paragraph_tempnorms**-0.5).dot(longest_paragraph_X)

longest_paragraph_n_data=numpy.shape(longest_paragraph_X)[0]
longest_paragraph_n_dimensions=numpy.shape(longest_paragraph_X)[1]


In [82]:
# report the 20 words with highest TF-IDF weight using the length-normalized frequency and smoothed idf
print("report the 20 words with highest TF-IDF weight using the length-normalized frequency and smoothed idf")
longest_paragraph_tf_idf_weights = numpy.squeeze(numpy.array(longest_paragraph_X[0, :].todense()))
longest_paragraph_highest_tf_idf_indices = numpy.argsort(-1*longest_paragraph_tf_idf_weights,axis=0)
# print(longest_paragraph_remainingvocabulary[longest_paragraph_highest_tf_idf_indices[0:20]])
# print(longest_paragraph_tf_idf_weights[longest_paragraph_highest_tf_idf_indices[0:20]])


report the 20 words with highest TF-IDF weight using the length-normalized frequency and smoothed idf


In [85]:
# Use the count statistics to compute the tf-idf matrix
longest_paragraph_tfidfmatrix=scipy.sparse.lil_matrix((longest_paragraph_n_docs,longest_paragraph_n_vocab))
# Let's use raw term count, and smoothed logarithmic idf
longest_paragraph_idfvector = numpy.squeeze(numpy.array(longest_paragraph_dfvector.todense()))
# count relative to the most frequent term
longest_paragraph_idfvector = 0.02 + 0.98*longest_paragraph_idfvector / numpy.max(longest_paragraph_idfvector)
for k in range(longest_paragraph_n_docs):
    # Combine the tf and idf terms
    # # longest_paragraph_tfidfmatrix[k,:]=longest_paragraph_tfmatrix[k,:]*longest_paragraph_idfvector
    # fixing dimensionality mismatch
    longest_paragraph_tempindices = numpy.nonzero(longest_paragraph_tfmatrix[k, :])[1]
    longest_paragraph_tfterm = numpy.squeeze(numpy.array(longest_paragraph_tfmatrix[k, longest_paragraph_tempindices].todense()))
    longest_paragraph_tfidfmatrix[k, longest_paragraph_tempindices] = longest_paragraph_tfterm * longest_paragraph_idfvector[longest_paragraph_tempindices]
#%% Use the TF-IDF matrix as data to be clustered
longest_paragraph_X=longest_paragraph_tfidfmatrix
# Normalize the documents to unit vector norm
longest_paragraph_tempnorms=numpy.squeeze(numpy.array(numpy.sum(longest_paragraph_X.multiply(longest_paragraph_X),axis=1)))
# If any documents have zero norm, avoid dividing them by zero
longest_paragraph_tempnorms[longest_paragraph_tempnorms==0]=1
longest_paragraph_tempnorms = numpy.array([longest_paragraph_tempnorms])
longest_paragraph_X=scipy.sparse.diags(longest_paragraph_tempnorms**-0.5).dot(longest_paragraph_X)

longest_paragraph_n_data=numpy.shape(longest_paragraph_X)[0]
longest_paragraph_n_dimensions=numpy.shape(longest_paragraph_X)[1]


In [84]:
# report the 20 words with highest TF-IDF weight using the logarithm of the count and smoothed idf
print("report the 20 words with highest TF-IDF weight using the count relative to the most frequent term and version proportional to the inverse of the document frequency")
longest_paragraph_tf_idf_weights = numpy.squeeze(numpy.array(longest_paragraph_X[0, :].todense()))
longest_paragraph_highest_tf_idf_indices = numpy.argsort(-1*longest_paragraph_tf_idf_weights,axis=0)
# print(longest_paragraph_remainingvocabulary[longest_paragraph_highest_tf_idf_indices[0:20]])
# print(longest_paragraph_tf_idf_weights[longest_paragraph_highest_tf_idf_indices[0:20]])

report the 20 words with highest TF-IDF weight using the count relative to the most frequent term and version proportional to the inverse of the document frequency


Discuss: Due to the problems of coding, which is "remainingvocabulary" length, I can't actually print the list.